### ISSUE TITLE
readme.md - evaluation.GetSummary - should be evaluation.PrintSummary

### ISSUE THREAD

**Issue by ZombieRunner** [breskos/gopher-learn#6]
in readme.md

evaluation.GetSummary("name of class1")
evaluation.GetSummary("name of class2")

Should read:
evaluation.PrintSummary("name of class1")
evaluation.PrintSummary("name of class2")

GetSummary was a function in the depricated gopher-neural project.

**Comment by breskos** [comment]
Thank you!
